# Generated by Django 6.0.2 on 2026-04-29 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to='reader_cards/'),
        ),
        migrations.AddField(
            model_name='reader',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reader',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reader',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reader',
            name='password_hash',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reader',
            name='session_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='reader',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
