# Generated by Django 6.0.5 on 2026-05-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_book_issue_count_book_reservation_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readerlibrarycard',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
